name: Starbound
version: '1.0'
author: "Atticus Zambrana"
main: family.zambrana.starbound.Starbound
api-version: '1.21'
commands:
  servers:
    description: View a list of all servers
  disguise:
    description: Nickname system
  staffchat:
    description: Send a message into the staff chat
    aliases: ["s"]
  whitelist:
    description: Modify the whitelist
  fly:
    description: "Fly into the sky"
  rank:
    description: Update a players rank on the server
  delhome:
    description: Allows a player to remove an old home
  sethome:
    description: Allows you to set a home
  home:
    description: Teleport to your home
  homes:
    description: Display a list of all of your homes
  teleport:
    aliases: ["tp"]
    description: Teleport to another player or teleport them to another player
  gamemode:
    aliases: ["gm"]
    description: Toggle your current gamemode