name: Starbound
version: '1.0'
author: "Atticus Zambrana"
main: family.zambrana.starbound.Starter
api-version: '1.21'
commands:
  fly:
    description: "Fly into the sky"
  rank:
    description: Update a players rank on the server
  sethome:
    description: Allows you to set a home
  home:
    description: Teleport to your home
  homes:
    description: Display a list of all of your homes